### PR TITLE
Refactor and Enchancements

### PR DESCRIPTION
**Pull request by polewskm**
Major Version Upgrade
* Added second package with signed assembly
* Refactored part definition to always wrap
* Added more unit tests

[Review on Reviewable](https://reviewable.io/reviews/ncodegroup/ncode.composition.disposableparts/1)

### CODE REVIEW

**Comment by Aberwyvern** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[NCode.Composition.DisposableParts.Signed/NCode.Composition.DisposableParts.Signed.csproj, line 37 \[r1\]](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1#-K7Hpy6fyoSTi4FQc5uz:-K7Hpy6fyoSTi4FQc5v-:2025791910) ([raw file](https://github.com/ncodegroup/ncode.composition.disposableparts/blob/99db1447b6d9df0e853b3437e2b5cdeb0d543882/NCode.Composition.DisposableParts.Signed/NCode.Composition.DisposableParts.Signed.csproj#L37)):*
If you are making NCodeGroup an entity should this be a single NCodeGroup SNK?
Also if you are sticking with NCodeGroup as the "organization" should the root namespace be NCodeGroup instead of NCode?

---

*[NCode.Composition.DisposableParts.Tests/CatalogTests.cs, line 65 \[r1\]](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1#-K7HsINGZrjKQThsL4FQ:-K7HsINGZrjKQThsL4FR:-83504707) ([raw file](https://github.com/ncodegroup/ncode.composition.disposableparts/blob/99db1447b6d9df0e853b3437e2b5cdeb0d543882/NCode.Composition.DisposableParts.Tests/CatalogTests.cs#L65)):*
Include the sharing qualification in the class name -- DummyNonDisposableNonShared 
Is the class NonShared. IDK from this context.

---

*[NCode.Composition.DisposableParts.Tests/CatalogTests.cs, line 76 \[r1\]](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1#-K7Ht-zntApCiUIEC8X1:-K7Ht-zntApCiUIEC8X2:-1915075294) ([raw file](https://github.com/ncodegroup/ncode.composition.disposableparts/blob/99db1447b6d9df0e853b3437e2b5cdeb0d543882/NCode.Composition.DisposableParts.Tests/CatalogTests.cs#L76)):*
Again include sharing qualification in the class name.
Here is where it starts to get confusing.
You have "DummyDisposable" here, "DummyDisposableShared" on the next one, and "DummyDisposableNonShared" on the next one. Does "DummyDisposable" have no sharing attribute? If so then I think I get it, but it may help to have the test name or class name somehow indicate that is what this case is covering.

---

*[NCode.Composition.DisposableParts.Tests/CatalogTests.cs, line 131 \[r1\]](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1#-K7Hu8QGLWt9prbcWZc9:-K7Hu8QHFoRwvUF92hmo:-2108520856) ([raw file](https://github.com/ncodegroup/ncode.composition.disposableparts/blob/99db1447b6d9df0e853b3437e2b5cdeb0d543882/NCode.Composition.DisposableParts.Tests/CatalogTests.cs#L131)):*
What do you mean by skips existing wrapper?
Since you are testing for AreSame it seems like it is testing for the fact that it doesn't create a new wrapper.
Shoudl it read CreateWrapper_UsesPreExistingWrapper?

---

*[NCode.Composition.DisposableParts.Tests/CatalogTests.cs, line 145 \[r1\]](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1#-K7Hv43WLL20bTWH8-Mp:-K7Hv43WLL20bTWH8-Mq:-817938906) ([raw file](https://github.com/ncodegroup/ncode.composition.disposableparts/blob/99db1447b6d9df0e853b3437e2b5cdeb0d543882/NCode.Composition.DisposableParts.Tests/CatalogTests.cs#L145)):*
Use DummyNonDisposable here instead, right?

---

*[NCode.Composition.DisposableParts.Tests/CatalogTests.cs, line 190 \[r1\]](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1#-K7HvY3Jls5KaWI813pk:-K7HvY3Jls5KaWI813pl:676926978) ([raw file](https://github.com/ncodegroup/ncode.composition.disposableparts/blob/99db1447b6d9df0e853b3437e2b5cdeb0d543882/NCode.Composition.DisposableParts.Tests/CatalogTests.cs#L190)):*
Nice

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1)*

**Comment by polewskm** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[NCode.Composition.DisposableParts.Signed/NCode.Composition.DisposableParts.Signed.csproj, line 37 \[r1\]](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1#-K7Hpy6fyoSTi4FQc5uz:-K7JJNqlJJsjHcaSOXp3:-1030041302) ([raw file](https://github.com/ncodegroup/ncode.composition.disposableparts/blob/99db1447b6d9df0e853b3437e2b5cdeb0d543882/NCode.Composition.DisposableParts.Signed/NCode.Composition.DisposableParts.Signed.csproj#L37)):*
Sure, I'll rename the SNK to the org entity. But I still prefer NCode for the root NS for brevity.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1)*

**Comment by polewskm** [comment]
Reviewed 11 of 15 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[NCode.Composition.DisposableParts.Signed/NCode.Composition.DisposableParts.Signed.csproj, line 37 \[r1\]](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1#-K7Hpy6fyoSTi4FQc5uz:-K7JLucQvYiN7u5mSi9L:-499146009) ([raw file](https://github.com/ncodegroup/ncode.composition.disposableparts/blob/99db1447b6d9df0e853b3437e2b5cdeb0d543882/NCode.Composition.DisposableParts.Signed/NCode.Composition.DisposableParts.Signed.csproj#L37)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1)*

**Comment by Aberwyvern** [comment]
Reviewed 14 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[NCode.Composition.DisposableParts.Signed/NCode.Composition.DisposableParts.Signed.csproj, line 37 \[r1\]](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1#-K7Hpy6fyoSTi4FQc5uz:-K7K1ALdsGeaiSYevKQ_:1462440858) ([raw file](https://github.com/ncodegroup/ncode.composition.disposableparts/blob/99db1447b6d9df0e853b3437e2b5cdeb0d543882/NCode.Composition.DisposableParts.Signed/NCode.Composition.DisposableParts.Signed.csproj#L37)):*
Kewl. Sounds fair

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1)*

**Comment by Aberwyvern** [comment]
Looks excellent. Thanks for putting this all together! You rock socks.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ncodegroup/ncode.composition.disposableparts/1#-:-K7K1RwJErOQHMMXTWUy:-215238695)*

**Pull request merged**
